// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Dashboard Design 8.3.11

#include "../ui.h"

void ui_comp_Slider2_create_hook(lv_obj_t * comp)
{
}
